package ch.tocco.soaptest.soap;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.1.0
 * 2025-02-13T07:59:24.010+01:00
 * Generated source version: 4.1.0
 *
 */
@WebServiceClient(name = "B2BService",
                  targetNamespace = "http://ch.swisspost.ebill.b2bservice")
public class B2BService_Service extends Service {


    public static final QName SERVICE = new QName("http://ch.swisspost.ebill.b2bservice", "B2BService");
    public static final QName UserNamePassword = new QName("http://ch.swisspost.ebill.b2bservice", "UserNamePassword");

    public B2BService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public B2BService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public B2BService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public B2BService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     *
     * @return
     *     returns B2BService
     */
    @WebEndpoint(name = "UserNamePassword")
    public B2BService getUserNamePassword() {
        return super.getPort(UserNamePassword, B2BService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns B2BService
     */
    @WebEndpoint(name = "UserNamePassword")
    public B2BService getUserNamePassword(WebServiceFeature... features) {
        return super.getPort(UserNamePassword, B2BService.class, features);
    }

}
