
package ch.tocco.soaptest.soap;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "B2BService", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface B2BService {


    /**
     * 
     * @param archiveData
     * @param billerID
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfInvoiceReport
     */
    @WebMethod(operationName = "GetInvoiceListBiller", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListBiller")
    @WebResult(name = "GetInvoiceListBillerResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetInvoiceListBiller", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceListBiller")
    @ResponseWrapper(localName = "GetInvoiceListBillerResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceListBillerResponse")
    public ArrayOfInvoiceReport getInvoiceListBiller(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData);

    /**
     * 
     * @param billDetail
     * @param billerID
     * @param transactionID
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfDownloadFile
     */
    @WebMethod(operationName = "GetInvoiceBiller", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceBiller")
    @WebResult(name = "GetInvoiceBillerResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetInvoiceBiller", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceBiller")
    @ResponseWrapper(localName = "GetInvoiceBillerResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceBillerResponse")
    public ArrayOfDownloadFile getInvoiceBiller(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "TransactionID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String transactionID,
        @WebParam(name = "BillDetail", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean billDetail);

    /**
     * 
     * @param archiveData
     * @param billerID
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfProtocolReport
     */
    @WebMethod(operationName = "GetProcessProtocolList", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocolList")
    @WebResult(name = "GetProcessProtocolListResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetProcessProtocolList", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetProcessProtocolList")
    @ResponseWrapper(localName = "GetProcessProtocolListResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetProcessProtocolListResponse")
    public ArrayOfProtocolReport getProcessProtocolList(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData);

    /**
     * 
     * @param archiveData
     * @param billerID
     * @param createDate
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfDownloadFile
     */
    @WebMethod(operationName = "GetProcessProtocol", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocol")
    @WebResult(name = "GetProcessProtocolResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetProcessProtocol", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetProcessProtocol")
    @ResponseWrapper(localName = "GetProcessProtocolResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetProcessProtocolResponse")
    public ArrayOfDownloadFile getProcessProtocol(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "CreateDate", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        XMLGregorianCalendar createDate,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData);

    /**
     * 
     * @param archiveData
     * @param billerID
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfProtocolReport
     */
    @WebMethod(operationName = "GetRegistrationProtocolList", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocolList")
    @WebResult(name = "GetRegistrationProtocolListResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetRegistrationProtocolList", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetRegistrationProtocolList")
    @ResponseWrapper(localName = "GetRegistrationProtocolListResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetRegistrationProtocolListResponse")
    public ArrayOfProtocolReport getRegistrationProtocolList(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData);

    /**
     * 
     * @param archiveData
     * @param billerID
     * @param createDate
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfDownloadFile
     */
    @WebMethod(operationName = "GetRegistrationProtocol", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocol")
    @WebResult(name = "GetRegistrationProtocolResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetRegistrationProtocol", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetRegistrationProtocol")
    @ResponseWrapper(localName = "GetRegistrationProtocolResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetRegistrationProtocolResponse")
    public ArrayOfDownloadFile getRegistrationProtocol(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "CreateDate", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        XMLGregorianCalendar createDate,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData);

    /**
     * 
     * @param billerID
     * @param invoices
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfProcessedInvoice
     */
    @WebMethod(operationName = "UploadFilesReport", action = "http://ch.swisspost.ebill.b2bservice/B2BService/UploadFilesReport")
    @WebResult(name = "UploadFilesReportResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "UploadFilesReport", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.UploadFilesReport")
    @ResponseWrapper(localName = "UploadFilesReportResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.UploadFilesReportResponse")
    public ArrayOfProcessedInvoice uploadFilesReport(
        @WebParam(name = "invoices", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        ArrayOfInvoice invoices,
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID);

    /**
     * 
     * @param parameter
     * @return
     *     returns ch.tocco.soaptest.soap.SearchInvoicesResponse2
     */
    @WebMethod(operationName = "SearchInvoices", action = "http://ch.swisspost.ebill.b2bservice/B2BService/SearchInvoices")
    @WebResult(name = "SearchInvoicesResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "SearchInvoices", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.SearchInvoices")
    @ResponseWrapper(localName = "SearchInvoicesResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.SearchInvoicesResponse")
    public SearchInvoicesResponse2 searchInvoices(
        @WebParam(name = "Parameter", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        SearchInvoiceParameter parameter);

    /**
     * 
     * @param billerID
     * @param recipientID
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfEBillRecipientSubscriptionStatus
     */
    @WebMethod(operationName = "GetEBillRecipientSubscriptionStatus", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStatus")
    @WebResult(name = "GetEBillRecipientSubscriptionStatusResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetEBillRecipientSubscriptionStatus", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetEBillRecipientSubscriptionStatus")
    @ResponseWrapper(localName = "GetEBillRecipientSubscriptionStatusResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetEBillRecipientSubscriptionStatusResponse")
    public ArrayOfEBillRecipientSubscriptionStatus getEBillRecipientSubscriptionStatus(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "RecipientID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String recipientID);

    /**
     * 
     * @param billerID
     * @param recipientID
     * @return
     *     returns ch.tocco.soaptest.soap.EBillRecipientSubscriptionStatusBulk
     */
    @WebMethod(operationName = "GetEBillRecipientSubscriptionStatusBulk", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStatusBulk")
    @WebResult(name = "GetEBillRecipientSubscriptionStatusBulkResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetEBillRecipientSubscriptionStatusBulk", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetEBillRecipientSubscriptionStatusBulk")
    @ResponseWrapper(localName = "GetEBillRecipientSubscriptionStatusBulkResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetEBillRecipientSubscriptionStatusBulkResponse")
    public EBillRecipientSubscriptionStatusBulk getEBillRecipientSubscriptionStatusBulk(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "RecipientID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        ArrayOfstring recipientID);

    /**
     * 
     * @param billerID
     * @param subscriptionInitiationEmailAddress
     * @return
     *     returns ch.tocco.soaptest.soap.EBillRecipientSubscriptionInitiation
     */
    @WebMethod(operationName = "InitiateEBillRecipientSubscription", action = "http://ch.swisspost.ebill.b2bservice/B2BService/InitiateEBillRecipientSubscription")
    @WebResult(name = "InitiateEBillRecipientSubscriptionResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "InitiateEBillRecipientSubscription", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.InitiateEBillRecipientSubscription")
    @ResponseWrapper(localName = "InitiateEBillRecipientSubscriptionResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.InitiateEBillRecipientSubscriptionResponse")
    public EBillRecipientSubscriptionInitiation initiateEBillRecipientSubscription(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "SubscriptionInitiationEmailAddress", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String subscriptionInitiationEmailAddress);

    /**
     * 
     * @param billerID
     * @param subscriptionInitiationActivationCode
     * @param subscriptionInitiationToken
     * @return
     *     returns ch.tocco.soaptest.soap.EBillRecipientSubscriptionConfirmation
     */
    @WebMethod(operationName = "ConfirmEBillRecipientSubscription", action = "http://ch.swisspost.ebill.b2bservice/B2BService/ConfirmEBillRecipientSubscription")
    @WebResult(name = "ConfirmEBillRecipientSubscriptionResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "ConfirmEBillRecipientSubscription", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.ConfirmEBillRecipientSubscription")
    @ResponseWrapper(localName = "ConfirmEBillRecipientSubscriptionResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.ConfirmEBillRecipientSubscriptionResponse")
    public EBillRecipientSubscriptionConfirmation confirmEBillRecipientSubscription(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "SubscriptionInitiationToken", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String subscriptionInitiationToken,
        @WebParam(name = "SubscriptionInitiationActivationCode", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String subscriptionInitiationActivationCode);

    /**
     * 
     * @param archiveData
     * @param billerID
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfBillerReport
     */
    @WebMethod(operationName = "GetBillerReportList", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReportList")
    @WebResult(name = "GetBillerReportListResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetBillerReportList", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetBillerReportList")
    @ResponseWrapper(localName = "GetBillerReportListResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetBillerReportListResponse")
    public ArrayOfBillerReport getBillerReportList(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData);

    /**
     * 
     * @param billerID
     * @param createDate
     * @param fileType
     * @return
     *     returns ch.tocco.soaptest.soap.DownloadFile
     */
    @WebMethod(operationName = "GetBillerReport", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReport")
    @WebResult(name = "GetBillerReportResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetBillerReport", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetBillerReport")
    @ResponseWrapper(localName = "GetBillerReportResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetBillerReportResponse")
    public DownloadFile getBillerReport(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "CreateDate", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String createDate,
        @WebParam(name = "FileType", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String fileType);

    /**
     * 
     * @param billerID
     * @param eBillAccountID
     * @param fileType
     * @param transactionID
     * @return
     *     returns ch.tocco.soaptest.soap.DownloadFile
     */
    @WebMethod(operationName = "GetInvoicePayer", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoicePayer")
    @WebResult(name = "GetInvoicePayerResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetInvoicePayer", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoicePayer")
    @ResponseWrapper(localName = "GetInvoicePayerResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoicePayerResponse")
    public DownloadFile getInvoicePayer(
        @WebParam(name = "eBillAccountID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String eBillAccountID,
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "TransactionID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String transactionID,
        @WebParam(name = "FileType", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String fileType);

    /**
     * 
     * @param archiveData
     * @param eBillAccountID
     * @return
     *     returns ch.tocco.soaptest.soap.ArrayOfInvoiceReport
     */
    @WebMethod(operationName = "GetInvoiceListPayer", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListPayer")
    @WebResult(name = "GetInvoiceListPayerResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "GetInvoiceListPayer", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceListPayer")
    @ResponseWrapper(localName = "GetInvoiceListPayerResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceListPayerResponse")
    public ArrayOfInvoiceReport getInvoiceListPayer(
        @WebParam(name = "eBillAccountID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String eBillAccountID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData);

    /**
     * 
     * @param billerID
     * @param eBillAccountID
     * @param errorTest
     * @param exceptionTest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecutePing", action = "http://ch.swisspost.ebill.b2bservice/B2BService/ExecutePing")
    @WebResult(name = "ExecutePingResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    @RequestWrapper(localName = "ExecutePing", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.ExecutePing")
    @ResponseWrapper(localName = "ExecutePingResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.ExecutePingResponse")
    public String executePing(
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String billerID,
        @WebParam(name = "eBillAccountID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        String eBillAccountID,
        @WebParam(name = "ErrorTest", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        Boolean errorTest,
        @WebParam(name = "ExceptionTest", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        Boolean exceptionTest);

}
