package ch.tocco.soaptest.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.0
 * 2025-02-13T07:59:23.970+01:00
 * Generated source version: 4.1.0
 *
 */
@WebService(targetNamespace = "http://ch.swisspost.ebill.b2bservice", name = "B2BService")
@XmlSeeAlso({ObjectFactory.class})
public interface B2BService {

    @WebMethod(operationName = "ConfirmEBillRecipientSubscription", action = "http://ch.swisspost.ebill.b2bservice/B2BService/ConfirmEBillRecipientSubscription")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/ConfirmEBillRecipientSubscription", output = "http://ch.swisspost.ebill.b2bservice/B2BService/ConfirmEBillRecipientSubscriptionResponse")
    @RequestWrapper(localName = "ConfirmEBillRecipientSubscription", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.ConfirmEBillRecipientSubscription")
    @ResponseWrapper(localName = "ConfirmEBillRecipientSubscriptionResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.ConfirmEBillRecipientSubscriptionResponse")
    @WebResult(name = "ConfirmEBillRecipientSubscriptionResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.EBillRecipientSubscriptionConfirmation confirmEBillRecipientSubscription(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "SubscriptionInitiationToken", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String subscriptionInitiationToken,
        @WebParam(name = "SubscriptionInitiationActivationCode", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String subscriptionInitiationActivationCode
    );

    @WebMethod(operationName = "GetBillerReport", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReport")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReport", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReportResponse")
    @RequestWrapper(localName = "GetBillerReport", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetBillerReport")
    @ResponseWrapper(localName = "GetBillerReportResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetBillerReportResponse")
    @WebResult(name = "GetBillerReportResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.DownloadFile getBillerReport(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "CreateDate", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String createDate,
        @WebParam(name = "FileType", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String fileType
    );

    @WebMethod(operationName = "ExecutePing", action = "http://ch.swisspost.ebill.b2bservice/B2BService/ExecutePing")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/ExecutePing", output = "http://ch.swisspost.ebill.b2bservice/B2BService/ExecutePingResponse")
    @RequestWrapper(localName = "ExecutePing", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.ExecutePing")
    @ResponseWrapper(localName = "ExecutePingResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.ExecutePingResponse")
    @WebResult(name = "ExecutePingResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public java.lang.String executePing(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "eBillAccountID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String eBillAccountID,
        @WebParam(name = "ErrorTest", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.Boolean errorTest,
        @WebParam(name = "ExceptionTest", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.Boolean exceptionTest
    );

    @WebMethod(operationName = "GetRegistrationProtocolList", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocolList")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocolList", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocolListResponse")
    @RequestWrapper(localName = "GetRegistrationProtocolList", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetRegistrationProtocolList")
    @ResponseWrapper(localName = "GetRegistrationProtocolListResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetRegistrationProtocolListResponse")
    @WebResult(name = "GetRegistrationProtocolListResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfProtocolReport getRegistrationProtocolList(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData
    );

    @WebMethod(operationName = "GetInvoiceBiller", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceBiller")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceBiller", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceBillerResponse")
    @RequestWrapper(localName = "GetInvoiceBiller", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceBiller")
    @ResponseWrapper(localName = "GetInvoiceBillerResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceBillerResponse")
    @WebResult(name = "GetInvoiceBillerResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfDownloadFile getInvoiceBiller(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "TransactionID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String transactionID,
        @WebParam(name = "BillDetail", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean billDetail
    );

    @WebMethod(operationName = "InitiateEBillRecipientSubscription", action = "http://ch.swisspost.ebill.b2bservice/B2BService/InitiateEBillRecipientSubscription")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/InitiateEBillRecipientSubscription", output = "http://ch.swisspost.ebill.b2bservice/B2BService/InitiateEBillRecipientSubscriptionResponse")
    @RequestWrapper(localName = "InitiateEBillRecipientSubscription", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.InitiateEBillRecipientSubscription")
    @ResponseWrapper(localName = "InitiateEBillRecipientSubscriptionResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.InitiateEBillRecipientSubscriptionResponse")
    @WebResult(name = "InitiateEBillRecipientSubscriptionResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.EBillRecipientSubscriptionInitiation initiateEBillRecipientSubscription(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "SubscriptionInitiationEmailAddress", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String subscriptionInitiationEmailAddress
    );

    @WebMethod(operationName = "GetRegistrationProtocol", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocol")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocol", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocolResponse")
    @RequestWrapper(localName = "GetRegistrationProtocol", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetRegistrationProtocol")
    @ResponseWrapper(localName = "GetRegistrationProtocolResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetRegistrationProtocolResponse")
    @WebResult(name = "GetRegistrationProtocolResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfDownloadFile getRegistrationProtocol(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "CreateDate", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        javax.xml.datatype.XMLGregorianCalendar createDate,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData
    );

    @WebMethod(operationName = "SearchInvoices", action = "http://ch.swisspost.ebill.b2bservice/B2BService/SearchInvoices")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/SearchInvoices", output = "http://ch.swisspost.ebill.b2bservice/B2BService/SearchInvoicesResponse")
    @RequestWrapper(localName = "SearchInvoices", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.SearchInvoices")
    @ResponseWrapper(localName = "SearchInvoicesResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.SearchInvoicesResponse")
    @WebResult(name = "SearchInvoicesResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.SearchInvoicesResponse2 searchInvoices(

        @WebParam(name = "Parameter", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        ch.tocco.soaptest.soap.SearchInvoiceParameter parameter
    );

    @WebMethod(operationName = "GetBillerReportList", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReportList")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReportList", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReportListResponse")
    @RequestWrapper(localName = "GetBillerReportList", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetBillerReportList")
    @ResponseWrapper(localName = "GetBillerReportListResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetBillerReportListResponse")
    @WebResult(name = "GetBillerReportListResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfBillerReport getBillerReportList(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData
    );

    @WebMethod(operationName = "UploadFilesReport", action = "http://ch.swisspost.ebill.b2bservice/B2BService/UploadFilesReport")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/UploadFilesReport", output = "http://ch.swisspost.ebill.b2bservice/B2BService/UploadFilesReportResponse")
    @RequestWrapper(localName = "UploadFilesReport", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.UploadFilesReport")
    @ResponseWrapper(localName = "UploadFilesReportResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.UploadFilesReportResponse")
    @WebResult(name = "UploadFilesReportResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfProcessedInvoice uploadFilesReport(

        @WebParam(name = "invoices", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        ch.tocco.soaptest.soap.ArrayOfInvoice invoices,
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID
    );

    @WebMethod(operationName = "GetEBillRecipientSubscriptionStatusBulk", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStatusBulk")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStatusBulk", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStatusBulkResponse")
    @RequestWrapper(localName = "GetEBillRecipientSubscriptionStatusBulk", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetEBillRecipientSubscriptionStatusBulk")
    @ResponseWrapper(localName = "GetEBillRecipientSubscriptionStatusBulkResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetEBillRecipientSubscriptionStatusBulkResponse")
    @WebResult(name = "GetEBillRecipientSubscriptionStatusBulkResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.EBillRecipientSubscriptionStatusBulk getEBillRecipientSubscriptionStatusBulk(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "RecipientID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        ch.tocco.soaptest.soap.ArrayOfstring recipientID
    );

    @WebMethod(operationName = "GetInvoiceListBiller", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListBiller")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListBiller", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListBillerResponse")
    @RequestWrapper(localName = "GetInvoiceListBiller", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceListBiller")
    @ResponseWrapper(localName = "GetInvoiceListBillerResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceListBillerResponse")
    @WebResult(name = "GetInvoiceListBillerResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfInvoiceReport getInvoiceListBiller(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData
    );

    @WebMethod(operationName = "GetProcessProtocolList", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocolList")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocolList", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocolListResponse")
    @RequestWrapper(localName = "GetProcessProtocolList", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetProcessProtocolList")
    @ResponseWrapper(localName = "GetProcessProtocolListResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetProcessProtocolListResponse")
    @WebResult(name = "GetProcessProtocolListResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfProtocolReport getProcessProtocolList(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData
    );

    @WebMethod(operationName = "GetProcessProtocol", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocol")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocol", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocolResponse")
    @RequestWrapper(localName = "GetProcessProtocol", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetProcessProtocol")
    @ResponseWrapper(localName = "GetProcessProtocolResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetProcessProtocolResponse")
    @WebResult(name = "GetProcessProtocolResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfDownloadFile getProcessProtocol(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "CreateDate", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        javax.xml.datatype.XMLGregorianCalendar createDate,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData
    );

    @WebMethod(operationName = "GetEBillRecipientSubscriptionStatus", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStatus")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStatus", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStatusResponse")
    @RequestWrapper(localName = "GetEBillRecipientSubscriptionStatus", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetEBillRecipientSubscriptionStatus")
    @ResponseWrapper(localName = "GetEBillRecipientSubscriptionStatusResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetEBillRecipientSubscriptionStatusResponse")
    @WebResult(name = "GetEBillRecipientSubscriptionStatusResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfEBillRecipientSubscriptionStatus getEBillRecipientSubscriptionStatus(

        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "RecipientID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String recipientID
    );

    @WebMethod(operationName = "GetInvoiceListPayer", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListPayer")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListPayer", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListPayerResponse")
    @RequestWrapper(localName = "GetInvoiceListPayer", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceListPayer")
    @ResponseWrapper(localName = "GetInvoiceListPayerResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoiceListPayerResponse")
    @WebResult(name = "GetInvoiceListPayerResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.ArrayOfInvoiceReport getInvoiceListPayer(

        @WebParam(name = "eBillAccountID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String eBillAccountID,
        @WebParam(name = "ArchiveData", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        boolean archiveData
    );

    @WebMethod(operationName = "GetInvoicePayer", action = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoicePayer")
    @Action(input = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoicePayer", output = "http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoicePayerResponse")
    @RequestWrapper(localName = "GetInvoicePayer", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoicePayer")
    @ResponseWrapper(localName = "GetInvoicePayerResponse", targetNamespace = "http://ch.swisspost.ebill.b2bservice", className = "ch.tocco.soaptest.soap.GetInvoicePayerResponse")
    @WebResult(name = "GetInvoicePayerResult", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
    public ch.tocco.soaptest.soap.DownloadFile getInvoicePayer(

        @WebParam(name = "eBillAccountID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String eBillAccountID,
        @WebParam(name = "BillerID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String billerID,
        @WebParam(name = "TransactionID", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String transactionID,
        @WebParam(name = "FileType", targetNamespace = "http://ch.swisspost.ebill.b2bservice")
        java.lang.String fileType
    );
}
